[project]
name = "datahub-ingest"
version = "1.0"
description = "DataHub custom recipe ingest pipeline"
readme = "README.md"
requires-python = ">=3.12,<3.15"

dependencies = [
    "acryl-datahub[dbt]>=1.3.1,<2.0",
]

[tool.ruff]
line-length = 100
lint.select = ["F", "E", "W", "I001"]
